chore: update builder info

diff --git a/core b/core
--- a/core
+++ b/core
@@ -101,7 +101,7 @@ install() {
 
   # see docker/setup-buildx-action
   local builder_name=builder-zmicro-package
-  
+
   # docker buildx inspect --builder $builder_name >>/dev/null
   # @TODO
   set +e
@@ -109,20 +109,32 @@ install() {
   if [ "$?" != "0" ]; then
     set -e
 
-    log::info "[$(timestamp)] creating a builder: $builder_name ..."
+    log::info "[$(timestamp)] creating builder: $builder_name ..."
     docker buildx create \
       --name ${builder_name} \
       --driver docker-container \
       --buildkitd-flags "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host" \
-      --use
+      --use >>/dev/null
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)] failed to create builder: $builder_name ."
+      return 1
+    fi
+
+    log::info "[$(timestamp)] succeed to create builder: $builder_name ."
   else
     set -e
   fi
 
-  local status=$(docker buildx inspect --bootstrap default | grep Status | awk '{print $2}')
+  local status=$(docker buildx inspect --bootstrap $builder_name | grep Status | awk '{print $2}')
   if [ "$status" != "running" ]; then
     log::info "[$(timestamp)] bootstraping builder: $builder_name ..."
     docker buildx inspect --bootstrap --builder $builder_name
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)] failed to bootstrap builder: $builder_name ."
+      return 1
+    fi
+
+    log::info "[$(timestamp)] succeed to bootstrap builder: $builder_name ."
   fi
 
   log::info "[$(timestamp)] inspecting builder: $builder_name ..."
